export enum UserRole {
    SALE_STAFF = 'SALE_STAFF',
    SALE_LEADER = 'SALE_LEADER',
    ACCOUNTING = 'ACCOUNTING',
    ADMIN = 'ADMIN',
}

export enum PaymentStatus {
    NEW = 'NEW',
    DRAFT = 'DRAFT',
    SUBMITTED = 'SUBMITTED',
    COMPLETED = 'COMPLETED',
    LOCKED = 'LOCKED',
}

export enum AuditAction {
    // Auth
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILED = 'LOGIN_FAILED',
    LOGOUT = 'LOGOUT',

    // User
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DEACTIVATED = 'USER_DEACTIVATED',
    PASSWORD_RESET = 'PASSWORD_RESET',

    // Payment
    PAYMENT_CREATED = 'PAYMENT_CREATED',
    PAYMENT_UPDATED = 'PAYMENT_UPDATED',
    PAYMENT_ASSIGNED = 'PAYMENT_ASSIGNED',
    PAYMENT_SUBMITTED = 'PAYMENT_SUBMITTED',
    PAYMENT_UNLOCKED = 'PAYMENT_UNLOCKED',
    PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',

    // Invoice
    INVOICE_CREATED = 'INVOICE_CREATED',
    INVOICE_UPDATED = 'INVOICE_UPDATED',
    INVOICE_DELETED = 'INVOICE_DELETED',
    INVOICE_LOCKED = 'INVOICE_LOCKED',
    INVOICE_UNLOCKED = 'INVOICE_UNLOCKED',

    // Import/Export
    IMPORT_STARTED = 'IMPORT_STARTED',
    IMPORT_COMPLETED = 'IMPORT_COMPLETED',
    IMPORT_FAILED = 'IMPORT_FAILED',
    EXPORT_REQUESTED = 'EXPORT_REQUESTED',
}
